services:
  postgres14:
    image: postgres:14
    container_name: kore-postgres
    restart: unless-stopped
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kore_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bruno -d kore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: kore-app
    restart: unless-stopped
    ports:
      - "8005:8005"
    env_file:
      - .env.docker
    depends_on:
      postgres14:
        condition: service_healthy

volumes:
  pgdata:
