[project]
name = "kore-product-manager"
version = "0.1.0"
description = "Simple product manager using Basecoat UI and Django."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.2",
    "django-allauth>=65.14.3",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.29.0",
    "gunicorn>=25.1.0",
    "pillow>=12.2.0",
    "psycopg>=3.3.2",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "ruff>=0.15.13",
    "uvicorn>=0.30.1",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "coverage>=7.13.4",
    "factory-boy>=3.3.3",
    "poethepoet>=0.41.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.12.0",
    "pytest-watch>=4.2.0",
]

[tool.poe.tasks]
npm-build = { shell = "npm run build" }
runserver = "python manage.py runserver"
migrate = { shell = "python manage.py makemigrations && python manage.py migrate" }
pytest = { shell = "pytest" }

ruff-fix = { shell = "ruff check . --fix" }
ruffer = { shell = "ruff check ." }

cov-run = "uv run coverage run -m pytest"
cov-report = "uv run coverage report"
cov-html = "uv run coverage html"

[tool.poe.tasks.test]
sequence = ["cov-run", "cov-report", "cov-html"]

# Ruff configurations
[tool.ruff]
line-length = 150
exclude = ["**/migrations/*.py"]

[tool.ruff.lint]
select = [
    "F",  # Pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "DJ", # flake8-django
    "TC", # flake8-type-checking
]
# Bloco pronto para futuras exceções

[tool.ruff.lint.per-file-ignores]
"**/tests/*.py" = ["E501"]

# Coverage configurations
[tool.poe.tasks.coverage]
sequence = ["cov-run", "cov-report", "cov-html"]

[tool.coverage.run]
source = ["products", "api", "partners", "kore-product-manager"]
omit = ["*/tests/*", "*/__pycache__/*", "*/migrations/*", "manage.py", "*/urls.py", "*/wsgi.py", "*/asgi.py"]

[tool.coverage.report]
show_missing = true
# Ignorar linhas vazias/comentários no cálculo
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "pass",
    "raise NotImplementedError",
]
fail_under = 90 # Falha se a cobertura total for menor que 90%
