[project]
name = "kore-product-manager"
version = "0.1.0"
description = "Simple product manager using Basecoat UI and Django."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.2",
    "django-allauth>=65.14.3",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.29.0",
    "gunicorn>=25.1.0",
    "psycopg>=3.3.2",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "ruff>=0.15.13",
    "uvicorn>=0.30.1",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "coverage>=7.13.4",
    "factory-boy>=3.3.3",
    "poethepoet>=0.41.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.12.0",
    "pytest-watch>=4.2.0",
]

[tool.poe.tasks]
npm_build = { shell = "npm run build" }
runserver = "python manage.py runserver"
migrate = { shell = "python manage.py makemigrations && python manage.py migrate" }
pytest = { shell = "pytest" }
coverage = { shell = "coverage run -m pytest" }
report = { shell = "coverage report" }
coveragehtml = { shell = "coverage html" }

[tool.poe.tasks.test]
sequence = ["coverage", "coveragehtml", "report"]

[tool.ruff]
line-length = 120
exclude = ["**/migrations/*.py"]

[tool.ruff.lint]
extend-select = [
    "DJ",       # flake8-django: Django-specific bugs
    "E",        # pycodestyle errors
    "F",        # Pyflakes
    "W",        # pycodestyle warnings
    "I",        # isort
    "UP",       # pyupgrade
    "B",        # flake8-bugbear
]

[tool.ruff.lint.per-file-ignores]
"**/tests/*.py" = ["E501"]
