# Generated by Django 6.0.2 on 2026-05-20 19:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rows_exported', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], max_length=20)),
                ('error_details', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Exportação',
                'verbose_name_plural': 'Logs de Exportação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('PARTIAL', 'Parcial'), ('FAILED', 'Falha')], max_length=20)),
                ('error_details', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Importação',
                'verbose_name_plural': 'Logs de Importação',
                'ordering': ['-created_at'],
            },
        ),
    ]
