# Generated by Django 6.0.2 on 2026-05-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
    ]
