# Generated by Django 6.0.2 on 2026-05-21 07:13

from django.db import migrations, models


def migrate_address_to_street(apps, schema_editor):
    Customer = apps.get_model("partners", "Customer")
    Supplier = apps.get_model("partners", "Supplier")

    for customer in Customer.objects.all():
        old_address = customer.address or ""
        if old_address and not customer.street:
            customer.street = old_address
            customer.save(update_fields=["street"])

    for supplier in Supplier.objects.all():
        old_address = supplier.address or ""
        if old_address and not supplier.street:
            supplier.street = old_address
            supplier.save(update_fields=["street"])


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_supplier_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customer',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='condicoes_pagamento_padrao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Condições de Pagamento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='inscricao_estadual',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='inscricao_municipal',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='prazo_entrega_medio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de Entrega Médio (dias)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real')], default='', max_length=20, verbose_name='Regime Tributário'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CEP'),
        ),
        migrations.RunPython(migrate_address_to_street, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
