# Generated by Django 6.0.2 on 2026-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_customer_address_remove_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Pessoa de Contato'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
    ]
