# Generated by Django 6.0.2 on 2026-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_customer_cpf_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=10, verbose_name='Status'),
        ),
    ]
