# Generated by Django 6.0.2 on 2026-05-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_cost_price_product_min_stock_level_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
