# Generated by Django 6.0.2 on 2026-05-21 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_cleanup_old_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cest',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='product',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='Código de Barras (EAN/GTIN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largura (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='product',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso Bruto (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso Líquido (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='profundidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profundidade (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SKU (Código Interno)'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('descontinuado', 'Descontinuado')], default='ativo', max_length=14, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('CX', 'Caixa'), ('L', 'Litro'), ('PCT', 'Pacote')], default='UN', max_length=3, verbose_name='Unidade de Medida'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('deposito', 'Depósito'), ('loja', 'Loja'), ('corredor', 'Corredor'), ('prateleira', 'Prateleira')], default='deposito', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
                'ordering': ['name'],
            },
        ),
    ]
