# Generated by Django 6.0.2 on 2026-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_altura_product_cest_product_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('descontinuado', 'Descontinuado')], default='ativo', max_length=14, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('CX', 'Caixa'), ('L', 'Litro'), ('PCT', 'Pacote')], default='UN', max_length=3, verbose_name='Unidade de Medida'),
        ),
    ]
