# Generated by Django 6.0.2 on 2026-05-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_migrate_stock_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_stock_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
