# Generated by Django 6.0.2 on 2026-05-21 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_min_stock_level_remove_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Product', 'Produto'), ('Category', 'Categoria'), ('StorageLocation', 'Local de Armazenamento'), ('Customer', 'Cliente'), ('Supplier', 'Fornecedor'), ('ProductMovement', 'Movimentação')], max_length=50, verbose_name='Formulário')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo')),
                ('field_label', models.CharField(blank=True, default='', max_length=200, verbose_name='Rótulo')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Campo',
                'verbose_name_plural': 'Configurações de Campos',
                'unique_together': {('user', 'model_name', 'field_name')},
            },
        ),
    ]
